name: Publish New Relic Application

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: nr1
        env:
          NR_USER_KEY: ${{ secrets.NR_USER_KEY }}
        id: nr1
        run: |
          curl -s https://cli.nr-ext.net/installer.sh | sudo bash
          npm install
          nr1 profiles:add --name tmp --api-key $NR_USER_KEY --region us
          nr1 nerdpack:info

      - name: update uuid
        if: failure()
        run: |
          nr1 nerdpack:uuid -gf

      - name: Update files
        if: failure()
        uses: stefanzweifel/git-auto-commit-action@v3.0.0
        with:
          commit_message: Update
          ref: ${{ github.head_ref }}

      - name: Publish
        continue-on-error: true
        if: always()
        run: |
          nr1 nerdpack:publish

      - name: Publish
        if: always()
        run: |
          sleep 10
          nr1 catalog:submit
